GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmlmbSIsImlhdCI6MTY2OTY1NzY5NywiZXhwIjoxNjY5NzQ0MDk3fQ.6YpU8QwzXte7gkk6QDjRe_niVxQcLUZ0lkpWYDxmqc8

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjY5NjU3NTI5fQ.J9ubxMdaU_7GA1TNMerrQn3076VKAEG8nBic2kbbzTM"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjY5NjU3NTI5fQ.J9ubxMdaU_7GA1TNMerrQn3076VKAEG8nBic2kbbzTM"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Kyle"
}